"""initial schema

Revision ID: 8118123df9b9
Revises: 
Create Date: 2026-06-10 16:42:26.867888

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '8118123df9b9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculty',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('specialization', sa.String(), nullable=True),
    sa.Column('max_credits', sa.Integer(), nullable=True),
    sa.Column('current_credits', sa.Integer(), nullable=True),
    sa.Column('data_source', sa.Enum('SIS', 'LMS', 'demo', name='datasource'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('programs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('degree_level', sa.String(), nullable=True),
    sa.Column('total_credits', sa.Integer(), nullable=True),
    sa.Column('duration_years', sa.Integer(), nullable=True),
    sa.Column('data_source', sa.Enum('SIS', 'LMS', 'demo', name='datasource'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alumni_mentors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('program_id', sa.String(), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('current_role', sa.String(), nullable=True),
    sa.Column('current_company', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('linkedin_profile', sa.String(), nullable=True),
    sa.Column('mentoring_capacity', sa.Integer(), nullable=True),
    sa.Column('current_mentees', sa.Integer(), nullable=True),
    sa.Column('mentee_student_ids', sa.JSON(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('data_source', sa.Enum('SIS', 'LMS', 'demo', name='datasource'), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.Column('semester', sa.String(), nullable=True),
    sa.Column('program_id', sa.String(), nullable=True),
    sa.Column('instructor_id', sa.String(), nullable=True),
    sa.Column('data_source', sa.Enum('SIS', 'LMS', 'demo', name='datasource'), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['faculty.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('graduation_requirements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('program_id', sa.String(), nullable=False),
    sa.Column('requirement_type', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('required_value', sa.Integer(), nullable=True),
    sa.Column('data_source', sa.Enum('SIS', 'LMS', 'demo', name='datasource'), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('program_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('year_level', sa.Integer(), nullable=True),
    sa.Column('credits_earned', sa.Integer(), nullable=True),
    sa.Column('gpa', sa.Float(), nullable=True),
    sa.Column('admission_term', sa.String(), nullable=True),
    sa.Column('data_source', sa.Enum('SIS', 'LMS', 'demo', name='datasource'), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('administrative_holds',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('hold_type', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('blocks_registration', sa.Boolean(), nullable=True),
    sa.Column('blocks_transcript', sa.Boolean(), nullable=True),
    sa.Column('placed_by', sa.String(), nullable=True),
    sa.Column('placed_date', sa.Date(), nullable=True),
    sa.Column('resolved_date', sa.Date(), nullable=True),
    sa.Column('data_source', sa.Enum('SIS', 'LMS', 'demo', name='datasource'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('career_pathways',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('target_role', sa.String(), nullable=True),
    sa.Column('target_industry', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('skills_gap', sa.JSON(), nullable=True),
    sa.Column('recommended_courses', sa.JSON(), nullable=True),
    sa.Column('target_companies', sa.JSON(), nullable=True),
    sa.Column('linkedin_profile', sa.String(), nullable=True),
    sa.Column('internship_target_semester', sa.String(), nullable=True),
    sa.Column('created_date', sa.Date(), nullable=True),
    sa.Column('data_source', sa.Enum('SIS', 'LMS', 'demo', name='datasource'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_aid_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('aid_type', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('semester', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('applied_date', sa.Date(), nullable=True),
    sa.Column('approved_date', sa.Date(), nullable=True),
    sa.Column('renewable', sa.Boolean(), nullable=True),
    sa.Column('renewal_conditions', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('data_source', sa.Enum('SIS', 'LMS', 'demo', name='datasource'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lms_signals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=False),
    sa.Column('semester', sa.String(), nullable=True),
    sa.Column('signal_date', sa.Date(), nullable=True),
    sa.Column('login_count_last_30_days', sa.Integer(), nullable=True),
    sa.Column('last_login_days_ago', sa.Integer(), nullable=True),
    sa.Column('assignment_submission_rate', sa.Float(), nullable=True),
    sa.Column('avg_quiz_score', sa.Float(), nullable=True),
    sa.Column('video_watch_rate', sa.Float(), nullable=True),
    sa.Column('forum_posts', sa.Integer(), nullable=True),
    sa.Column('risk_flag', sa.Boolean(), nullable=True),
    sa.Column('data_source', sa.Enum('SIS', 'LMS', 'demo', name='datasource'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('onboarding_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('task_name', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('data_source', sa.Enum('SIS', 'LMS', 'demo', name='datasource'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prerequisites',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=False),
    sa.Column('prerequisite_course_id', sa.String(), nullable=False),
    sa.Column('min_grade', sa.String(), nullable=True),
    sa.Column('data_source', sa.Enum('SIS', 'LMS', 'demo', name='datasource'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['prerequisite_course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_sections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=False),
    sa.Column('section_code', sa.String(), nullable=True),
    sa.Column('instructor_id', sa.String(), nullable=True),
    sa.Column('semester', sa.String(), nullable=True),
    sa.Column('days', sa.JSON(), nullable=True),
    sa.Column('start_time', sa.String(), nullable=True),
    sa.Column('end_time', sa.String(), nullable=True),
    sa.Column('room', sa.String(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('enrolled', sa.Integer(), nullable=True),
    sa.Column('data_source', sa.Enum('SIS', 'LMS', 'demo', name='datasource'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['faculty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('bloom_level', sa.String(), nullable=True),
    sa.Column('assessment_method', sa.String(), nullable=True),
    sa.Column('data_source', sa.Enum('SIS', 'LMS', 'demo', name='datasource'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sponsorship_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('sponsor_name', sa.String(), nullable=True),
    sa.Column('sponsor_full_name', sa.String(), nullable=True),
    sa.Column('program_id', sa.String(), nullable=True),
    sa.Column('coverage_type', sa.String(), nullable=True),
    sa.Column('amount_per_semester', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('application_date', sa.Date(), nullable=True),
    sa.Column('approval_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('data_source', sa.Enum('SIS', 'LMS', 'demo', name='datasource'), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_course_progress',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('program_id', sa.String(), nullable=True),
    sa.Column('credits_earned', sa.Integer(), nullable=True),
    sa.Column('credits_required', sa.Integer(), nullable=True),
    sa.Column('credits_deficit', sa.Integer(), nullable=True),
    sa.Column('expected_credits_at_year_3', sa.Integer(), nullable=True),
    sa.Column('core_credits_earned', sa.Integer(), nullable=True),
    sa.Column('math_credits_earned', sa.Integer(), nullable=True),
    sa.Column('capstone_completed', sa.Boolean(), nullable=True),
    sa.Column('internship_hours_completed', sa.Integer(), nullable=True),
    sa.Column('on_track', sa.Boolean(), nullable=True),
    sa.Column('projected_graduation', sa.String(), nullable=True),
    sa.Column('expected_graduation', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('data_source', sa.Enum('SIS', 'LMS', 'demo', name='datasource'), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('support_cases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('case_type', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('assigned_to_faculty_id', sa.String(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('opened_date', sa.Date(), nullable=True),
    sa.Column('closed_date', sa.Date(), nullable=True),
    sa.Column('data_source', sa.Enum('SIS', 'LMS', 'demo', name='datasource'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_faculty_id'], ['faculty.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=True),
    sa.Column('workflow_type', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('created_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('data_source', sa.Enum('SIS', 'LMS', 'demo', name='datasource'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cohort_slo_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=False),
    sa.Column('slo_id', sa.String(), nullable=False),
    sa.Column('course_code', sa.String(), nullable=True),
    sa.Column('semester', sa.String(), nullable=False),
    sa.Column('proficiency_rate', sa.Float(), nullable=True),
    sa.Column('avg_score', sa.Float(), nullable=True),
    sa.Column('cohort_size', sa.Integer(), nullable=True),
    sa.Column('data_source', sa.Enum('SIS', 'LMS', 'demo', name='datasource'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['slo_id'], ['slos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enrollments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=False),
    sa.Column('section_id', sa.String(), nullable=True),
    sa.Column('semester', sa.String(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('data_source', sa.Enum('SIS', 'LMS', 'demo', name='datasource'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['schedule_sections.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interventions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('intervention_type', sa.String(), nullable=True),
    sa.Column('recommended_by', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_date', sa.Date(), nullable=True),
    sa.Column('approved_date', sa.Date(), nullable=True),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('data_source', sa.Enum('SIS', 'LMS', 'demo', name='datasource'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['support_cases.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slo_assessments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('slo_id', sa.String(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=True),
    sa.Column('semester', sa.String(), nullable=True),
    sa.Column('assessment_date', sa.Date(), nullable=True),
    sa.Column('assessed_students', sa.Integer(), nullable=True),
    sa.Column('proficient_count', sa.Integer(), nullable=True),
    sa.Column('proficiency_rate', sa.Float(), nullable=True),
    sa.Column('avg_score', sa.Float(), nullable=True),
    sa.Column('data_source', sa.Enum('SIS', 'LMS', 'demo', name='datasource'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['slo_id'], ['slos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_slo_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('slo_id', sa.String(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=True),
    sa.Column('semester', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('proficient', sa.Boolean(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=True),
    sa.Column('data_source', sa.Enum('SIS', 'LMS', 'demo', name='datasource'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['slo_id'], ['slos.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_slo_results')
    op.drop_table('slo_assessments')
    op.drop_table('interventions')
    op.drop_table('enrollments')
    op.drop_table('cohort_slo_history')
    op.drop_table('workflow_items')
    op.drop_table('support_cases')
    op.drop_table('student_course_progress')
    op.drop_table('sponsorship_records')
    op.drop_table('slos')
    op.drop_table('schedule_sections')
    op.drop_table('prerequisites')
    op.drop_table('onboarding_tasks')
    op.drop_table('lms_signals')
    op.drop_table('financial_aid_records')
    op.drop_table('career_pathways')
    op.drop_table('administrative_holds')
    op.drop_table('students')
    op.drop_table('graduation_requirements')
    op.drop_table('courses')
    op.drop_table('alumni_mentors')
    op.drop_table('programs')
    op.drop_table('faculty')
    # ### end Alembic commands ###
    sa.Enum(name='datasource').drop(op.get_bind(), checkfirst=True)
